export const RESOURCE_UI_LANGUAGES = Object.freeze(['en', 'es', 'fr', 'it', 'ca']);

export const RESOURCE_UI_LABELS = Object.freeze({
  en: {
    audience: 'Audience',
    region: 'Region',
    level: 'Level',
    readingTime: 'Reading time',
    relatedTopics: 'Related topics',
    relatedPages: 'Related resources',
    nextStep: 'Next step',
    talkToAquaVerify: 'Talk to AquaVerify',
    faqTitle: 'Frequently asked questions',
    screenshotsTitle: 'Resource visuals',
    editorialTitle: 'Editorial information',
    editorialType: 'Document type',
    writtenBy: 'Written by',
    reviewedBy: 'Reviewed by',
    published: 'Published',
    lastReviewed: 'Last technical review',
    originalAuthors: 'Original study authors',
    originalSource: 'Original source',
    primarySource: 'Primary source',
    peerReview: 'Peer-review status',
    relation: 'Relationship to AquaVerify',
    limitations: 'Limitations',
    interests: 'Interests',
    download: 'Download',
    openWhitepaper: 'Open whitepaper',
    downloadChecklist: 'Download checklist',
    related: 'Related',
    backToResources: 'Back to resources',
    checklist: 'Checklist',
    recommendedLinks: 'Recommended links',
    version: 'Version',
    associatedHtmlResource: 'Associated HTML resource',
    evidenceToRetain: 'Evidence to retain',
    responsiblePerson: 'Responsible person',
    status: 'Status',
    notes: 'Notes',
    resource: 'Resource',
    objective: 'Objective',
    scope: 'Scope',
    howToUse: 'How to use this checklist',
    controls: 'Controls to verify',
    next: 'Suggested next step',
    sources: 'Sources and links',
    page: 'Page',
    prepared: 'Prepared for water microbiology, traceability and product selection conversations.',
    disclaimer: 'This document is technical orientation material. Method validation, accreditation, competent authority requirements and the quality system of each organization remain decisive.',
    statusCompliant: 'Compliant',
    statusPartial: 'Partial',
    statusNonCompliant: 'Non-compliant',
    statusNotApplicable: 'Not applicable',
    pdfAuthor: 'AquaVerify',
    pdfCreator: 'AquaVerify resource checklist generator',
    pdfSubject: 'Water microbiology checklist for technical orientation',
    pdfKeywords: 'AquaVerify, water microbiology, checklist, traceability',
    htmlResourceUrl: 'HTML resource URL'
  },
  es: {
    audience: 'Audiencia',
    region: 'Región',
    level: 'Nivel',
    readingTime: 'Tiempo de lectura',
    relatedTopics: 'Temas relacionados',
    relatedPages: 'Recursos relacionados',
    nextStep: 'Siguiente paso',
    talkToAquaVerify: 'Hablar con AquaVerify',
    faqTitle: 'Preguntas frecuentes',
    screenshotsTitle: 'Visuales del recurso',
    editorialTitle: 'Información editorial',
    editorialType: 'Tipo de documento',
    writtenBy: 'Escrito por',
    reviewedBy: 'Revisado por',
    published: 'Publicado',
    lastReviewed: 'Última revisión técnica',
    originalAuthors: 'Autores del estudio original',
    originalSource: 'Fuente original',
    primarySource: 'Fuente primaria',
    peerReview: 'Estado de revisión por pares',
    relation: 'Relación con AquaVerify',
    limitations: 'Limitaciones',
    interests: 'Declaración de intereses',
    download: 'Descargar',
    openWhitepaper: 'Abrir whitepaper',
    downloadChecklist: 'Descargar checklist',
    related: 'Relacionado',
    backToResources: 'Volver a recursos',
    checklist: 'Checklist',
    recommendedLinks: 'Enlaces recomendados',
    version: 'Versión',
    associatedHtmlResource: 'Recurso HTML asociado',
    evidenceToRetain: 'Evidencia que conservar',
    responsiblePerson: 'Responsable',
    status: 'Estado',
    notes: 'Notas',
    resource: 'Recurso',
    objective: 'Objetivo',
    scope: 'Alcance',
    howToUse: 'Cómo usar este checklist',
    controls: 'Controles a verificar',
    next: 'Siguiente paso sugerido',
    sources: 'Fuentes y enlaces',
    page: 'Página',
    prepared: 'Preparado para conversaciones de microbiología del agua, trazabilidad y selección de producto.',
    disclaimer: 'Este documento es material de orientación técnica. La validación de método, acreditación, autoridad competente y sistema de calidad de cada organización siguen siendo decisivos.',
    statusCompliant: 'Cumple',
    statusPartial: 'Parcial',
    statusNonCompliant: 'No cumple',
    statusNotApplicable: 'No aplica',
    pdfAuthor: 'AquaVerify',
    pdfCreator: 'Generador de checklists de recursos AquaVerify',
    pdfSubject: 'Checklist de microbiología del agua para orientación técnica',
    pdfKeywords: 'AquaVerify, microbiología del agua, checklist, trazabilidad',
    htmlResourceUrl: 'URL del recurso HTML'
  },
  fr: {
    audience: 'Public cible',
    region: 'Région',
    level: 'Niveau',
    readingTime: 'Temps de lecture',
    relatedTopics: 'Sujets associés',
    relatedPages: 'Ressources associées',
    nextStep: 'Étape suivante',
    talkToAquaVerify: 'Parler à AquaVerify',
    faqTitle: 'Questions fréquentes',
    screenshotsTitle: 'Visuels de la ressource',
    editorialTitle: 'Informations éditoriales',
    editorialType: 'Type de document',
    writtenBy: 'Rédigé par',
    reviewedBy: 'Relu par',
    published: 'Publié',
    lastReviewed: 'Dernière revue technique',
    originalAuthors: 'Auteurs de l’étude originale',
    originalSource: 'Source originale',
    primarySource: 'Source primaire',
    peerReview: 'Statut d’évaluation par les pairs',
    relation: 'Relation avec AquaVerify',
    limitations: 'Limites',
    interests: 'Déclaration d’intérêts',
    download: 'Télécharger',
    openWhitepaper: 'Ouvrir le whitepaper',
    downloadChecklist: 'Télécharger la checklist',
    related: 'Associé',
    backToResources: 'Retour aux ressources',
    checklist: 'Checklist',
    recommendedLinks: 'Liens recommandés',
    version: 'Version',
    associatedHtmlResource: 'Ressource HTML associée',
    evidenceToRetain: 'Preuve à conserver',
    responsiblePerson: 'Responsable',
    status: 'Statut',
    notes: 'Notes',
    resource: 'Ressource',
    objective: 'Objectif',
    scope: 'Périmètre',
    howToUse: 'Comment utiliser cette checklist',
    controls: 'Contrôles à vérifier',
    next: 'Étape suivante suggérée',
    sources: 'Sources et liens',
    page: 'Page',
    prepared: 'Préparé pour les échanges microbiologie de l’eau, traçabilité et sélection produit.',
    disclaimer: 'Ce document est un support d’orientation technique. La validation méthode, l’accréditation, l’autorité compétente et le système qualité de chaque organisation restent déterminants.',
    statusCompliant: 'Conforme',
    statusPartial: 'Partiel',
    statusNonCompliant: 'Non conforme',
    statusNotApplicable: 'Non applicable',
    pdfAuthor: 'AquaVerify',
    pdfCreator: 'Générateur de checklists ressources AquaVerify',
    pdfSubject: 'Checklist de microbiologie de l’eau pour orientation technique',
    pdfKeywords: 'AquaVerify, microbiologie de l’eau, checklist, traçabilité',
    htmlResourceUrl: 'URL de la ressource HTML'
  },
  it: {
    audience: 'Pubblico di riferimento',
    region: 'Regione',
    level: 'Livello',
    readingTime: 'Tempo di lettura',
    relatedTopics: 'Temi correlati',
    relatedPages: 'Risorse correlate',
    nextStep: 'Passo successivo',
    talkToAquaVerify: 'Parla con AquaVerify',
    faqTitle: 'Domande frequenti',
    screenshotsTitle: 'Visual della risorsa',
    editorialTitle: 'Informazioni editoriali',
    editorialType: 'Tipo di documento',
    writtenBy: 'Scritto da',
    reviewedBy: 'Revisionato da',
    published: 'Pubblicato',
    lastReviewed: 'Ultima revisione tecnica',
    originalAuthors: 'Autori dello studio originale',
    originalSource: 'Fonte originale',
    primarySource: 'Fonte primaria',
    peerReview: 'Stato peer-review',
    relation: 'Relazione con AquaVerify',
    limitations: 'Limitazioni',
    interests: 'Dichiarazione di interessi',
    download: 'Scarica',
    openWhitepaper: 'Apri whitepaper',
    downloadChecklist: 'Scarica checklist',
    related: 'Correlato',
    backToResources: 'Torna alle risorse',
    checklist: 'Checklist',
    recommendedLinks: 'Link consigliati',
    version: 'Versione',
    associatedHtmlResource: 'Risorsa HTML associata',
    evidenceToRetain: 'Evidenza da conservare',
    responsiblePerson: 'Responsabile',
    status: 'Stato',
    notes: 'Note',
    resource: 'Risorsa',
    objective: 'Obiettivo',
    scope: 'Ambito',
    howToUse: 'Come usare questa checklist',
    controls: 'Controlli da verificare',
    next: 'Prossimo passo suggerito',
    sources: 'Fonti e link',
    page: 'Pagina',
    prepared: 'Preparata per conversazioni su microbiologia dell’acqua, tracciabilità e selezione prodotto.',
    disclaimer: 'Questo documento è materiale di orientamento tecnico. Validazione metodo, accreditamento, autorità competente e sistema qualità di ogni organizzazione restano decisivi.',
    statusCompliant: 'Conforme',
    statusPartial: 'Parziale',
    statusNonCompliant: 'Non conforme',
    statusNotApplicable: 'Non applicabile',
    pdfAuthor: 'AquaVerify',
    pdfCreator: 'Generatore di checklist risorse AquaVerify',
    pdfSubject: 'Checklist di microbiologia dell’acqua per orientamento tecnico',
    pdfKeywords: 'AquaVerify, microbiologia dell’acqua, checklist, tracciabilità',
    htmlResourceUrl: 'URL della risorsa HTML'
  },
  ca: {
    audience: 'Públic objectiu',
    region: 'Regió',
    level: 'Nivell',
    readingTime: 'Temps de lectura',
    relatedTopics: 'Temes relacionats',
    relatedPages: 'Recursos relacionats',
    nextStep: 'Següent pas',
    talkToAquaVerify: 'Parlar amb AquaVerify',
    faqTitle: 'Preguntes freqüents',
    screenshotsTitle: 'Visuals del recurs',
    editorialTitle: 'Informació editorial',
    editorialType: 'Tipus de document',
    writtenBy: 'Escrit per',
    reviewedBy: 'Revisat per',
    published: 'Publicat',
    lastReviewed: 'Última revisió tècnica',
    originalAuthors: 'Autors de l’estudi original',
    originalSource: 'Font original',
    primarySource: 'Font primària',
    peerReview: 'Estat de revisió per parells',
    relation: 'Relació amb AquaVerify',
    limitations: 'Limitacions',
    interests: 'Declaració d’interessos',
    download: 'Descarregar',
    openWhitepaper: 'Obrir whitepaper',
    downloadChecklist: 'Descarregar checklist',
    related: 'Relacionat',
    backToResources: 'Tornar a recursos',
    checklist: 'Checklist',
    recommendedLinks: 'Enllaços recomanats',
    version: 'Versió',
    associatedHtmlResource: 'Recurs HTML associat',
    evidenceToRetain: 'Evidència que cal conservar',
    responsiblePerson: 'Responsable',
    status: 'Estat',
    notes: 'Notes',
    resource: 'Recurs',
    objective: 'Objectiu',
    scope: 'Abast',
    howToUse: 'Com utilitzar aquest checklist',
    controls: 'Controls a verificar',
    next: 'Següent pas suggerit',
    sources: 'Fonts i enllaços',
    page: 'Pàgina',
    prepared: 'Preparat per a converses de microbiologia de l’aigua, traçabilitat i selecció de producte.',
    disclaimer: 'Aquest document és material d’orientació tècnica. La validació de mètode, acreditació, autoritat competent i sistema de qualitat de cada organització continuen sent decisius.',
    statusCompliant: 'Compleix',
    statusPartial: 'Parcial',
    statusNonCompliant: 'No compleix',
    statusNotApplicable: 'No aplica',
    pdfAuthor: 'AquaVerify',
    pdfCreator: 'Generador de checklists de recursos AquaVerify',
    pdfSubject: 'Checklist de microbiologia de l’aigua per a orientació tècnica',
    pdfKeywords: 'AquaVerify, microbiologia de l’aigua, checklist, traçabilitat',
    htmlResourceUrl: 'URL del recurs HTML'
  }
});

const BASE_LABEL_KEYS = Object.freeze(Object.keys(RESOURCE_UI_LABELS.en));

export function assertCompleteResourceUiLabels() {
  const errors = [];
  for (const lang of RESOURCE_UI_LANGUAGES) {
    const labels = RESOURCE_UI_LABELS[lang];
    if (!labels) {
      errors.push(`Missing resource UI labels for ${lang}`);
      continue;
    }
    const keys = Object.keys(labels);
    const missing = BASE_LABEL_KEYS.filter((key) => !Object.prototype.hasOwnProperty.call(labels, key));
    const extra = keys.filter((key) => !BASE_LABEL_KEYS.includes(key));
    if (missing.length) errors.push(`${lang} missing labels: ${missing.join(', ')}`);
    if (extra.length) errors.push(`${lang} has unknown labels: ${extra.join(', ')}`);
    for (const key of BASE_LABEL_KEYS) {
      if (!String(labels[key] || '').trim()) errors.push(`${lang}.${key} is empty`);
    }
  }
  if (errors.length) {
    throw new Error(errors.join('\n'));
  }
  return true;
}

export function getResourceUiLabels(lang) {
  assertCompleteResourceUiLabels();
  if (!RESOURCE_UI_LABELS[lang]) {
    throw new Error(`Unsupported resource UI language: ${lang}`);
  }
  return RESOURCE_UI_LABELS[lang];
}

export function getResourceUiLabel(lang, key) {
  const labels = getResourceUiLabels(lang);
  if (!Object.prototype.hasOwnProperty.call(labels, key)) {
    throw new Error(`Missing resource UI label: ${lang}.${key}`);
  }
  return labels[key];
}
